### ISSUE TITLE
一个示例的 `docker-compose.yaml` 文件

### ISSUE THREAD

**Issue by Aincvy** [HoPGoldy/cube-diary#6]
```yaml
version: '3'
services:
  cube-diary:
    image: node:slim
    container_name: cube-diary
    ports:
      - 3700:3700
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "cd /app &&
             npm install -g cube-diary &&
             cube-diary run"

```

放到任意目录之后， 执行 `sudo docker compose up -d`  即可启动。    

成功启动之后的目录是这样的： 
```
.
├── config.json
├── docker-compose.yaml
└── .storage
    ├── cube-diary.db
    ├── dbVersion
    ├── jwtSecret
    └── replayAttackSecret

1 directory, 6 files

```
